name: Deploy to Amazon EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Deploy to Amazon EC2
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: '13.112.68.176'
        SSH_USERNAME: 'ec2-user'
        SOURCE: '.'
        TARGET: '/var/www/html/your-app-directory'
        EXCLUDE: '/.github/,/vendor/,/.env'
